version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: backend
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    networks:
#      - backend
#    restart: unless-stopped
#    env_file:
#      - .env

volumes:
  postgres_data:

networks:
  backend:
    name: backend
